#!/bin/bash

printf "\e[36m<Git>:: \033[0m"
printf "Fetching the latest code before building the new version\n"
git pull origin main

printf "Composer dump autoload\n"
composer clear
composer dump-autoload


printf "Other artisan commands\n"
php artisan optimize
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan cache:clear
php artisan clear-compiled
php artisan storage:link
php artisan queue:restart
chmod 755 -R storage/
chmod 777 -R storage/logs/*
chmod 777 -R storage/logs
chown www-data:www-data -R storage/*
supervisorctl restart all
